# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c9b69ed60f2358026a306d98c7a472ec92fc6c9eba2b8268969e66c843d9628a077d148c653113c10232f180669c214e78107129b801352cfd92a4deed6f3b

test:
  secret_key_base: 8efd5f0989af3c09c6f7b353d33075382ccbb1721beb13dec8b57eb3ca06c45fe84bf5d91aba5d08046b5f1fa9015386a4d8ae67983687b681f665db292e4fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
